# Generated by Django 3.1.2 on 2020-10-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reddit_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=10)),
                ('reddit_title', models.TextField(default='')),
                ('reddit_comments', models.BigIntegerField()),
                ('reddit_username', models.CharField(max_length=50)),
                ('reddit_score', models.BigIntegerField()),
                ('reddit_domain', models.TextField(default='')),
                ('reddit_user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reddit_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=10)),
                ('reddit_body', models.TextField(default='')),
                ('reddit_username', models.CharField(max_length=50)),
            ],
        ),
    ]
