    # Generated by Django 3.1.2 on 2020-10-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditsaver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddit_links',
            name='reddit_body',
        ),
        migrations.AddField(
            model_name='reddit_data',
            name='reddit_body',
            field=models.TextField(default=''),
        ),
    ]
