# Generated by Django 3.1.2 on 2020-10-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditsaver', '0002_auto_20201006_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit_data',
            name='reddit_subred',
            field=models.CharField(default='', max_length=50),
        ),
    ]
