# Generated by Django 3.1.2 on 2020-10-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditsaver', '0003_reddit_data_reddit_subred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddit_data',
            name='reddit_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
