# Generated by Django 3.1.2 on 2020-10-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditsaver', '0004_auto_20201006_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reddit_links',
        ),
        migrations.RemoveField(
            model_name='reddit_data',
            name='reddit_user',
        ),
        migrations.AddField(
            model_name='reddit_data',
            name='reddit_link',
            field=models.BooleanField(default=False),
        ),
    ]
