# Generated by Django 3.1.2 on 2020-10-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditsaver', '0005_auto_20201006_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit_data',
            name='reddit_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
