# Generated by Django 3.1.2 on 2020-10-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditsaver', '0006_reddit_data_reddit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reddit_data',
            old_name='reddit_body',
            new_name='Reddit_Body',
        ),
        migrations.RenameField(
            model_name='reddit_data',
            old_name='reddit_comments',
            new_name='Reddit_Comments',
        ),
        migrations.RenameField(
            model_name='reddit_data',
            old_name='reddit_domain',
            new_name='Reddit_Domain',
        ),
        migrations.RenameField(
            model_name='reddit_data',
            old_name='reddit_id',
            new_name='Reddit_Id',
        ),
        migrations.RenameField(
            model_name='reddit_data',
            old_name='reddit_link',
            new_name='Reddit_Link',
        ),
        migrations.RenameField(
            model_name='reddit_data',
            old_name='reddit_score',
            new_name='Reddit_Score',
        ),
        migrations.RenameField(
            model_name='reddit_data',
            old_name='reddit_subred',
            new_name='Reddit_Subred',
        ),
        migrations.RenameField(
            model_name='reddit_data',
            old_name='reddit_title',
            new_name='Reddit_Title',
        ),
        migrations.RenameField(
            model_name='reddit_data',
            old_name='reddit_user',
            new_name='Reddit_User',
        ),
        migrations.RenameField(
            model_name='reddit_data',
            old_name='reddit_username',
            new_name='Reddit_Username',
        ),
    ]
